### PR TITLE
New `materialscloud-iframe` template

### LINKED ISSUE #15: No header template
In conversations between @ltalirz, @asle85 and myself it seems the easiest way of implementing Voilà applications into the dokku server to be used as MaterialsCloud tools is to remove the header in this template and put in the application using an `iframe`.

However, this is still under discussion, but this issue is here to follow the decisions taken within the MaterialsCloud team.

### PR DESCRIPTION
**Pull request by CasperWA**
Closes #15 

This adds a second template `materialscloud-iframe`.
It is set up alongside the regular `materialscloud` template. By passing `--template=materialscloud-iframe` to the `voila` command, the new template will be used.

It implements iframe handling similar to what is done in [`tools-barebone`](https://github.com/materialscloud-org/tools-barebone).
It also removes the MaterialsCloud header and breadcrumb.

The template files are set up such that all files that are similar to the `materialscloud` template are symlinks.

See the template in action with the OPTIMADE Client [here](http://optimadeclient.matcloud.xyz).

---

Missing:
- [x] "Hosted by Materials Cloud" footer.

### CODE REVIEW

**Comment by CasperWA** [comment]
I have sorted out the commits. It should _not_ be squash+merged at this point, but rather merged either with a merge commit message or using `--ff-only` from your own terminal.

**Comment by CasperWA** [comment]
@ltalirz and @asle85 do you have the possibility to try this new template on the Materials Cloud (dev-tools/dev-dokku)? I can update the OPTIMADE Client on dev-dokku to use the new template?

**Comment by ltalirz** [comment]
> do you have the possibility to try this new template on the Materials Cloud (dev-tools/dev-dokku)? I can update the OPTIMADE Client on dev-dokku to use the new template?

Absolutely, just push it to dev-dokku (you might also want to add the link to it here for the Pr review)

**Comment by CasperWA** [comment]
> > do you have the possibility to try this new template on the Materials Cloud (dev-tools/dev-dokku)? I can update the OPTIMADE Client on dev-dokku to use the new template?
> 
> Absolutely, just push it to dev-dokku (you might also want to add the link to it here for the Pr review)

I made it work.
You can see the result [here](http://optimadeclient.matcloud.xyz). The link has been added to the OP as well.

**Comment by CasperWA** [comment]
I should say that so far the "hosted" footer is _very_ minimalistic and not nice looking.
If anyone wants to give a go at making it nice, feel free to push commits to the `lite` branch, updating it.
Otherwise, I suggest to perhaps make another PR after this one has been merged/based on the `lite` branch.

**Review by dou-du — APPROVED** [review]

**Comment by CasperWA** [comment]
@ltalirz Can you confirm the iframing works with this implementation?

**Comment by ltalirz** [comment]
Yes, it's being used here: http://dev-www.materialscloud.org/tools/optimadeclient.

I would probably suggest to use the Materials Cloud logo somewhere in the footer, but you can also already merge it as-is

**Comment by CasperWA** [comment]
> Yes, it's being used here: http://dev-www.materialscloud.org/tools/optimadeclient.

Awesome!

> I would probably suggest to use the Materials Cloud logo somewhere in the footer, but you can also already merge it as-is

Updated to use the horizontal Materials Cloud logo:

image

**Review by ltalirz — APPROVED** [review]

**Comment by ltalirz** [comment]
Just as an aside: this is what the mybinder guys do for this purpose https://github.com/jupyterhub/mybinder.org-deploy/issues/1462

**Pull request merged**
